services:
  admin-ui:
    hostname: admin-ui
    container_name: admin-ui
    image: admin-ui:local
  map-service:
    hostname: map-service
    container_name: map-service
    image: map-service:local
    # TODO: bind the directory from where to look for image, instead of a specific image file
    volumes:
      - type: bind
        source: ./map-service/map_4500_21232.png
        target: /opt/map_4500_21232.png
        bind:
          create_host_path: false
  rcon-ws-proxy:
    hostname: rcon-ws-proxy
    container_name: rcon-ws-proxy
    image: rcon-ws-proxy:local
  tls-proxy:
    image: tls-proxy:local
    container_name: tls-proxy
    hostname: tls-proxy
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/fullchain1.pem
        target: /etc/nginx/tls.crt
        bind:
          create_host_path: false
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/privkey1.pem
        target: /etc/nginx/tls.key
        bind:
          create_host_path: false
