services:
  rust-server-with-nc:
    image: ghcr.io/jalho/reindeerland/rust-server-with-nc:alpha-1
    container_name: reindeerland
    env_file:
      - .env
    hostname: reindeerland
    ports:
      - 28015:28015/udp
      - 28017:28017/udp
      - 28082:28082/tcp
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RDS_STEAMCMD_INSTALL_DIRPATH}
        target: /steamcmd
        bind:
          create_host_path: false
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 28082 || exit 1"]
      interval: 1m
      retries: 20
      start_period: 30m
      timeout: 10s
    restart: always
  admin-ui:
    hostname: admin-ui
    container_name: admin-ui
    image: ghcr.io/jalho/reindeerland/admin-ui:alpha-1
  map-service:
    hostname: map-service
    container_name: map-service
    image: ghcr.io/jalho/reindeerland/map-service:alpha-1
    command: node server.mjs 80 /opt/images
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_MAP_IMAGE_DIR_PATH}
        target: /opt/images/
        bind:
          create_host_path: false
  player-detail-service:
    hostname: player-detail-service
    container_name: player-detail-service
    image: ghcr.io/jalho/reindeerland/player-detail-service:alpha-1
    command: node main.js 80 /opt/server/ip-locs.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_IPINFO_DISK_STORE_FILEPATH}
        target: /opt/server/ip-locs.json
        bind:
          create_host_path: false
  rcon-ws-proxy:
    hostname: rcon-ws-proxy
    container_name: rcon-ws-proxy
    image: ghcr.io/jalho/reindeerland/rcon-ws-proxy:alpha-1
    env_file:
      - .env
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
  tls-proxy:
    depends_on:
      rcon-ws-proxy:
        condition: service_healthy
      map-service:
        condition: service_healthy
      admin-ui:
        condition: service_healthy
      player-detail-service:
        condition: service_healthy
    image: ghcr.io/jalho/reindeerland/tls-proxy:alpha-1
    container_name: tls-proxy
    hostname: tls-proxy
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ${DOCKER_HOST_TLS_CERT_FILEPATH}
        target: /etc/nginx/tls.crt
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HOST_TLS_KEY_FILEPATH}
        target: /etc/nginx/tls.key
        bind:
          create_host_path: false
  logprocessor:
    image: ghcr.io/jalho/reindeerland/logprocessor:alpha-1
    command: node main.mjs logs/ discord-hooks.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RUSTDEDICATED_LOGS_DIR}
        target: /opt/run/logs
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HOST_DISCORD_HOOKS_FILEPATH}
        target: /opt/run/discord-hooks.json
        bind:
          create_host_path: false
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
    container_name: logprocessor
