services:
  rust-server-with-nc:
    networks:
      reindeerland-net: null
    image: ghcr.io/jalho/reindeerland/rust-server-with-nc:alpha-1
    container_name: reindeerland
    env_file:
      - .env
    hostname: reindeerland
    ports:
      - 28015:28015/udp
      - 28017:28017/udp
      - 28082:28082/tcp
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RDS_STEAMCMD_INSTALL_DIRPATH}
        target: /steamcmd
        bind:
          create_host_path: false
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 28082 || exit 1"]
      interval: 1m
      retries: 20
      start_period: 30m
      timeout: 10s
    restart: always

networks:
  reindeerland-net:
    name: reindeerland-net
