services:
  admin-ui:
    hostname: admin-ui
    container_name: admin-ui
    image: admin-ui:local
  map-service:
    hostname: map-service
    container_name: map-service
    image: map-service:local
    command: node server.mjs 80 /opt/images
    volumes:
      - type: bind
        source: ~/images/map_4500_10443.png
        target: /opt/images/map_4500_10443.png
        bind:
          create_host_path: false
  player-detail-service:
    hostname: player-detail-service
    container_name: player-detail-service
    image: player-detail-service:local
    command: node main.js 80 /opt/server/ip-locs.json
    volumes:
      - type: bind
        source: ~/temp/ip-locs.json
        target: /opt/server/ip-locs.json
        bind:
          create_host_path: false
  rcon-ws-proxy:
    hostname: rcon-ws-proxy
    container_name: rcon-ws-proxy
    image: rcon-ws-proxy:local
    environment:
      - SECRET_PASSWORD_HASH=${SECRET_PASSWORD_HASH}
      - SECRET_TOKEN_SIGNING=${SECRET_TOKEN_SIGNING}
      - RCON_WS_UPSTREAM_URL=${RCON_WS_UPSTREAM_URL}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - IPINFO_APIKEY=${IPINFO_APIKEY}
  tls-proxy:
    depends_on:
      - rcon-ws-proxy
      - map-service
      - admin-ui
      - player-detail-service
    image: tls-proxy:local
    container_name: tls-proxy
    hostname: tls-proxy
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/fullchain1.pem
        target: /etc/nginx/tls.crt
        bind:
          create_host_path: false
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/privkey1.pem
        target: /etc/nginx/tls.key
        bind:
          create_host_path: false
