services:
  rust-server-with-nc:
    image: rust-server-with-nc:local
    container_name: reindeerland
    env_file:
      - .env
    hostname: reindeerland
    ports:
      - 28015:28015/udp
      - 28017:28017/udp
      - 28082:28082/tcp
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RDS_STEAMCMD_INSTALL_DIRPATH}
        target: /steamcmd
        bind:
          create_host_path: false
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 28082 || exit 1"]
      interval: 1m
      retries: 20
      start_period: 30m
      timeout: 10s
    restart: always
  admin-ui:
    hostname: admin-ui
    container_name: admin-ui
    image: admin-ui:local
  map-service:
    hostname: map-service
    container_name: map-service
    image: map-service:local
    command: node server.mjs 80 /opt/images
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_MAP_IMAGE_DIR_PATH}
        target: /opt/images/
        bind:
          create_host_path: false
  player-detail-service:
    hostname: player-detail-service
    container_name: player-detail-service
    image: player-detail-service:local
    command: node main.js 80 /opt/server/ip-locs.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_IPINFO_DISK_STORE_FILEPATH}
        target: /opt/server/ip-locs.json
        bind:
          create_host_path: false
  rcon-ws-proxy:
    hostname: rcon-ws-proxy
    container_name: rcon-ws-proxy
    image: rcon-ws-proxy:local
    env_file:
      - .env
  tls-proxy:
    depends_on:
      - rcon-ws-proxy
      - map-service
      - admin-ui
      - player-detail-service
    image: tls-proxy:local
    container_name: tls-proxy
    hostname: tls-proxy
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/fullchain1.pem
        target: /etc/nginx/tls.crt
        bind:
          create_host_path: false
      - type: bind
        source: ~/temp-certbot/archive/sandbox.reindeerland.eu/privkey1.pem
        target: /etc/nginx/tls.key
        bind:
          create_host_path: false
  logprocessor:
    image: logprocessor:local
    command: node main.mjs logs/ discord-hooks.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RUSTDEDICATED_LOGS_DIR}
        target: /opt/run/logs
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HOST_DISCORD_HOOKS_FILEPATH}
        target: /opt/run/discord-hooks.json
        bind:
          create_host_path: false
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
    container_name: logprocessor
