services:
  admin-ui:
    hostname: admin-ui
    container_name: admin-ui
    image: ghcr.io/jalho/reindeerland/admin-ui:alpha-1
  map-service:
    networks:
      reindeerland-net: null
    hostname: map-service
    container_name: map-service
    image: ghcr.io/jalho/reindeerland/map-service:alpha-1
    command: node server.mjs 80 /opt/images
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_MAP_IMAGE_DIR_PATH}
        target: /opt/images/
        bind:
          create_host_path: false
  player-detail-service:
    networks:
      reindeerland-net: null
    hostname: player-detail-service
    container_name: player-detail-service
    image: ghcr.io/jalho/reindeerland/player-detail-service:alpha-1
    command: node main.js 80 /opt/server/ip-locs.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_IPINFO_DISK_STORE_FILEPATH}
        target: /opt/server/ip-locs.json
        bind:
          create_host_path: false
  rcon-ws-proxy:
    networks:
      reindeerland-net: null
    hostname: rcon-ws-proxy
    container_name: rcon-ws-proxy
    image: ghcr.io/jalho/reindeerland/rcon-ws-proxy:alpha-1
    env_file:
      - .env
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
  tls-proxy:
    networks:
      reindeerland-net: null
    image: ghcr.io/jalho/reindeerland/tls-proxy:alpha-1
    container_name: tls-proxy
    hostname: tls-proxy
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ${DOCKER_HOST_TLS_CERT_FILEPATH}
        target: /etc/nginx/tls.crt
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HOST_TLS_KEY_FILEPATH}
        target: /etc/nginx/tls.key
        bind:
          create_host_path: false
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
  logprocessor:
    image: ghcr.io/jalho/reindeerland/logprocessor:alpha-1
    command: node main.mjs logs/ discord-hooks.json
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DOCKER_HOST_RUSTDEDICATED_LOGS_DIR}
        target: /opt/run/logs
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HOST_DISCORD_HOOKS_FILEPATH}
        target: /opt/run/discord-hooks.json
        bind:
          create_host_path: false
    depends_on:
      rust-server-with-nc:
        condition: service_healthy
    container_name: logprocessor

networks:
  reindeerland-net:
    name: reindeerland-net
    external: true
